version: '3'


services:
    database:
        image: mysql:${MYSQL_VERSION}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
    
    php:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        depends_on:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - composer:/root/.composer
            - ./:/var/www
            - symfony_cache:/var/www/html/app/cache
        links:
            - database
        depends_on:
            - database

    web:
        image: nginx:alpine
        working_dir: /var/www
        links:
            - php
        depends_on:
            - php
        ports:
            - ${HTTPD_LOCAL_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf


    pma:
        image: phpmyadmin/phpmyadmin:${PMA_VERSION}
        environment:
            PMA_HOST: database
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${PMA_LOCAL_PORT}:80


volumes:
    mysql:
        driver: 'local'
    composer:
        driver: 'local'
    symfony_cache:
        driver: 'local'
    

