<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922170025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE profile_preference (category VARCHAR(255) NOT NULL, label VARCHAR(60) NOT NULL, value VARCHAR(200) NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A02870EA76ED395 ON profile_preference (user_id)');
        $this->addSql('CREATE TABLE profile_size (label VARCHAR(60) NOT NULL, value VARCHAR(60) NOT NULL, note VARCHAR(200) DEFAULT NULL, sort_order INT NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4108ABFEA76ED395 ON profile_size (user_id)');
        $this->addSql('CREATE TABLE social_identity (provider VARCHAR(255) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_social_identity_provider_subject ON social_identity (provider, provider_user_id)');
        $this->addSql('CREATE INDEX IDX_E4A47DE8A76ED395 ON social_identity (user_id)');
        $this->addSql('CREATE TABLE verification_code (purpose VARCHAR(255) NOT NULL, code_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attempts INT NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E821C39FA76ED395 ON verification_code (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE profile_preference ADD CONSTRAINT FK_9A02870EA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_size ADD CONSTRAINT FK_4108ABFEA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_identity ADD CONSTRAINT FK_E4A47DE8A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verification_code ADD CONSTRAINT FK_E821C39FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ALTER display_name DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE profile_preference DROP CONSTRAINT FK_9A02870EA76ED395');
        $this->addSql('ALTER TABLE profile_size DROP CONSTRAINT FK_4108ABFEA76ED395');
        $this->addSql('ALTER TABLE social_identity DROP CONSTRAINT FK_E4A47DE8A76ED395');
        $this->addSql('ALTER TABLE verification_code DROP CONSTRAINT FK_E821C39FA76ED395');
        $this->addSql('DROP TABLE profile_preference');
        $this->addSql('DROP TABLE profile_size');
        $this->addSql('DROP TABLE social_identity');
        $this->addSql('DROP TABLE verification_code');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE app_user ALTER display_name SET NOT NULL');
    }
}
